name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
     - shell: bash
       env: SUPER_SECRET: ${{ secrets.RUN_MODE }}
       run: |
         echo "$SUPER_SECRET"
